[package]
name = "yfnutool-macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "yfnutool_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "2.0.96"
tree-sitter = "0.24.5"
tree-sitter-nu = { path = "../tree-sitter-nu" }
